### ISSUE TITLE
core refactor 

### ISSUE THREAD

**Issue by rowanibrahem** [Alaanaser714/chatApp#2]
ليه الasset images فاضية و الصورة مش محطوطة جواها ؟ و ليه colors جوه constants ؟ هي بتكون جوه الthemes 
انت حاطط مرة جوه theme و مرة جوه constants هي جوه theme بس و فين الstyles اللي جواها الخطوط و الخط مش في الmain ؟
ياريت لو فيه مش فاهم حاجة تعرفني او تعدلهم و ترفع التعديل الجديد 
![image](https://github.com/user-attachments/assets/047bdd59-aca6-4b2e-9592-f833497beea4)

**Comment by Alaanaser714** [comment]
تمام عدلت كل حاجه بس مش فاهم ازاي احط الخط في main  وبالتالي يطبق ع كلوووو

**Comment by rowanibrahem** [comment]
MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
          textTheme: GoogleFonts.interTextTheme(),
          useMaterial3: true,
        ),
في text theme بتحدد الخط العام للتطبيق زي ما كنت شارحه

**Comment by Alaanaser714** [comment]
طب انا دلوقتي منزل الخط عادي مش من googleFont 
كدا   textTheme: GoogleFonts.interTextTheme()
هعمل اي هنا بقي

**Comment by Alaanaser714** [comment]
done
