### ISSUE TITLE
features refactor 

### ISSUE THREAD

**Issue by rowanibrahem** [Alaanaser714/chatApp#3]
ايه التقسيمة دي ؟
انت عاملهم العكس و مش مظبوطة ياريت تسمع فيديو الشرح تاني و تعيده و لو سمعت و مش فاهم ياريت تبعتلي لان دي مش صح 
![image](https://github.com/user-attachments/assets/d1c01cfb-3471-40f4-aa1f-8f6fc5b8ebaf)

**Comment by Alaanaser714** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/44dcf4d5-4596-41cb-abdf-e2c766768aac)
حضرتك هي دي التقسيمه بتاعتي اللي انا عاملها كدا صح ولا لا علشان الفايل من جوه فاضي فا مش بيظهر ف الرفع

**Comment by Alaanaser714** [comment]
تمام هعدلها وهرفع

**Comment by Alaanaser714** [comment]
done
